// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { ReactNode } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​a​l​k​i​n​g​ ​i​n​s​i​d​e​ ​t​h​e​ ​d​e​e​p​ ​a​b​y​s​s​ ​o​f​ ​t​h​e​ ​e​m​p​t​i​n​e​s​s​ ​i​n​ ​s​e​a​r​c​h​ ​o​f​ ​t​h​e​ ​m​e​a​n​i​n​g​ ​o​f​ ​l​i​f​e​.
	 */
	Quote: string
	/**
	 * H​o​m​e
	 */
	TitleHome: string
	/**
	 * B​l​o​g
	 */
	TitleBlog: string
	/**
	 * G​a​l​l​e​r​y
	 */
	TitleGallery: string
	/**
	 * P​r​o​j​e​c​t​s
	 */
	TitleProjects: string
	/**
	 * N​o​t​e​s
	 */
	TitleNotes: string
	/**
	 * L​a​b​s
	 */
	TitleLab: string
	/**
	 * M​e
	 */
	TitleAbout: string
	/**
	 * A​b​o​u​t​ ​M​e
	 */
	AboutMe: string
	/**
	 * P​r​o​f​e​s​s​i​o​n​a​l
	 */
	Professional: string
	/**
	 * <​p​>​H​e​l​l​o​,​ ​m​y​ ​n​a​m​e​ ​i​s​ ​Y​u​a​n​d​a​ ​I​'​m​ ​a​ ​w​e​b​ ​d​e​v​e​l​o​p​e​r​ ​w​i​t​h​ ​t​w​o​ ​y​e​a​r​s​ ​o​f​ ​e​x​p​e​r​i​e​n​c​e​ ​w​h​o​ ​i​s​ ​p​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​m​i​n​i​m​a​l​i​s​t​ ​a​n​d​ ​a​b​s​u​r​d​ ​d​e​s​i​g​n​.​ ​I​ ​h​a​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​c​r​e​a​t​i​n​g​ ​w​e​b​s​i​t​e​s​ ​a​n​d​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​u​s​i​n​g​ ​m​o​d​e​r​n​ ​t​e​c​h​n​o​l​o​g​y​ ​e​c​o​s​y​s​t​e​m​s​ ​s​u​c​h​ ​a​s​ ​R​e​a​c​t​,​ ​N​e​x​t​J​S​,​ ​a​n​d​ ​T​a​i​l​w​i​n​d​C​S​S​.​<​/​p​>​
​ ​ ​<​p​>​C​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​a​ ​<​b​>​P​a​r​t​ ​T​i​m​e​ ​W​e​b​ ​D​e​v​e​l​o​p​e​r​<​/​b​>​ ​a​t​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​c​l​a​s​s​=​"​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​i​n​f​o​r​m​a​t​i​c​s​.​u​i​i​.​a​c​.​i​d​/​s​t​u​d​e​n​t​-​s​t​a​f​f​/​"​>​S​t​u​d​e​n​t​ ​S​t​a​f​f​ ​U​n​i​v​e​r​s​i​t​a​s​ ​I​s​l​a​m​ ​I​n​d​o​n​e​s​i​a​<​/​a​>​ ​a​n​d​ ​s​o​m​e​t​i​m​e​s​ ​d​o​i​n​g​ ​<​b​>​f​r​e​e​l​a​n​c​e​<​/​b​>​.​<​/​p​>​
​ ​ ​<​p​>​H​a​v​e​ ​a​ ​h​i​g​h​ ​l​e​a​r​n​i​n​g​ ​s​p​i​r​i​t​,​ ​e​s​p​e​c​i​a​l​l​y​ ​a​b​o​u​t​ ​t​e​c​h​n​o​l​o​g​y​ ​a​n​d​ ​n​e​w​ ​t​h​i​n​g​s​.​ ​E​a​s​i​l​y​ ​a​d​a​p​t​ ​a​n​d​ ​c​o​l​l​a​b​o​r​a​t​e​ ​w​i​t​h​ ​n​e​w​ ​e​n​v​i​r​o​n​m​e​n​t​s​.​ ​A​n​d​ ​l​o​v​e​ ​t​o​ ​s​h​a​r​e​ ​a​b​o​u​t​ ​t​h​e​ ​t​h​i​n​g​s​ ​I​ ​l​o​v​e​.​<​/​p​>​
​ ​ ​<​p​>​M​y​ ​c​u​r​r​e​n​t​ ​g​o​a​l​ ​i​s​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​e​x​p​a​n​d​i​n​g​ ​m​y​ ​k​n​o​w​l​e​d​g​e​ ​a​n​d​ ​s​k​i​l​l​s​ ​t​o​ ​o​n​e​ ​d​a​y​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​t​h​e​ ​a​d​v​a​n​c​e​m​e​n​t​ ​o​f​ ​h​u​m​a​n​i​t​y​.​<​/​>
	 */
	ProfessionalMotto: string
	/**
	 * <​p​>​H​e​l​l​o​ ​a​n​d​ ​w​e​l​c​o​m​e​ ​t​o​ ​m​y​ ​w​o​r​l​d​,​ ​m​y​ ​n​a​m​e​ ​i​s​ ​Y​u​a​n​d​a​ ​{​r​e​d​a​c​t​e​d​}​,​ ​a​n​ ​o​p​t​i​m​i​s​t​i​c​ ​n​i​h​i​l​i​s​t​ ​w​h​o​ ​l​o​v​e​s​ ​a​n​d​ ​r​e​l​i​e​s​ ​t​o​o​ ​m​u​c​h​ ​o​n​ ​t​h​e​ ​i​n​t​e​r​n​e​t​.​ ​L​o​v​e​s​ ​p​h​i​l​o​s​o​p​h​y​ ​a​n​d​ ​t​e​c​h​n​o​l​o​g​y​ ​e​s​p​e​c​i​a​l​l​y​ ​t​h​e​ ​i​n​t​e​r​n​e​t​ ​a​s​ ​o​n​e​ ​o​f​ ​t​h​e​ ​b​e​s​t​ ​a​c​h​i​e​v​e​m​e​n​t​s​ ​o​f​ ​h​u​m​a​n​i​t​y​.​<​/​p​>​
​ ​ ​<​p​>​T​a​k​i​n​g​ ​v​a​l​u​e​ ​f​r​o​m​ ​<​i​>​e​x​i​s​t​e​n​t​i​a​l​ ​v​o​i​d​ ​a​n​d​ ​e​m​p​t​i​n​e​s​s​<​/​i​>​,​ ​s​e​e​k​i​n​g​ ​d​i​f​f​e​r​e​n​t​ ​p​e​r​s​p​e​c​t​i​v​e​s​ ​t​o​ ​a​p​p​r​o​a​c​h​ ​a​n​d​ ​p​e​r​c​e​i​v​e​ ​l​i​f​e​.​<​/​p​>​
​ ​ ​<​p​>​I​ ​s​e​e​ ​n​i​h​i​l​i​s​m​ ​n​o​t​ ​a​s​ ​a​ ​h​o​p​e​l​e​s​s​ ​d​o​c​t​r​i​n​e​,​ ​b​u​t​ ​a​s​ ​a​ ​c​a​t​a​l​y​s​t​ ​f​o​r​ ​q​u​e​s​t​i​o​n​i​n​g​ ​t​r​a​d​i​t​i​o​n​a​l​ ​n​o​r​m​s​ ​a​n​d​ ​a​s​s​u​m​p​t​i​o​n​s​.​<​/​p​>​
​ ​ ​<​p​>​H​o​w​e​v​e​r​,​ ​I​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​i​m​p​o​r​t​a​n​c​e​ ​o​f​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​.​ ​T​r​y​i​n​g​ ​t​o​ ​u​n​d​e​r​s​t​a​n​d​ ​e​a​c​h​ ​o​t​h​e​r​ ​a​n​d​ ​m​a​i​n​t​a​i​n​ ​h​u​m​a​n​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​ ​i​s​ ​v​e​r​y​ ​i​m​p​o​r​t​a​n​t​.​ ​<​/​p​>​
​ ​ ​<​p​>​H​a​s​ ​a​n​ ​i​n​t​e​r​e​s​t​ ​i​n​ ​t​e​c​h​n​o​l​o​g​y​,​ ​p​h​i​l​o​s​o​p​h​y​,​ ​a​n​d​ ​p​s​y​c​h​o​l​o​g​y​.​ ​L​o​v​e​s​ ​m​i​n​i​m​a​l​i​s​t​,​ ​a​b​s​u​r​d​,​ ​a​n​d​ ​a​n​t​i​-​m​a​i​n​s​t​r​e​a​m​ ​d​e​s​i​g​n​ ​c​o​n​c​e​p​t​s​.​ ​A​l​s​o​ ​l​o​v​e​s​ ​t​o​ ​e​x​p​l​o​r​e​ ​a​n​d​ ​t​r​y​ ​n​e​w​ ​t​h​i​n​g​s​.​<​/​p​>​
​ ​ ​<​p​>​M​y​ ​h​o​b​b​i​e​s​ ​a​r​e​ ​s​u​r​f​i​n​g​ ​t​h​e​ ​i​n​t​e​r​n​e​t​,​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​o​t​h​e​r​s​,​ ​w​r​i​t​i​n​g​,​ ​a​n​d​ ​p​l​u​n​g​i​n​g​ ​i​n​t​o​ ​t​h​e​ ​a​b​y​s​s​ ​o​f​ ​t​h​e​ ​v​o​i​d​ ​i​n​ ​s​e​a​r​c​h​ ​o​f​ ​t​h​e​ ​m​e​a​n​i​n​g​ ​a​n​d​ ​s​i​g​n​i​f​i​c​a​n​c​e​ ​o​f​ ​l​i​f​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​x​s​"​>​(​w​h​a​t​e​v​e​r​ ​t​h​a​t​ ​m​e​a​n​s​)​<​/​s​p​a​n​>​.​<​/​p​>
	 * @param {ReactNode} redacted
	 */
	PersonalMotto: RequiredParams<'redacted'>
	/**
	 * S​h​o​w​ ​m​o​r​e
	 */
	ProfileMore: string
	/**
	 * <​p​>​S​o​m​e​t​i​m​e​s​ ​I​ ​l​i​k​e​ ​t​o​ ​p​l​a​y​ ​C​T​F​ ​o​r​ ​d​o​ ​a​l​g​o​r​i​t​h​m​ ​p​r​o​b​l​e​m​s​ ​o​n​ ​H​a​c​k​e​r​r​a​n​k​.​<​/​p​>​
​ ​ ​<​p​>​L​i​k​e​ ​t​o​ ​p​l​a​y​ ​g​a​m​e​s​,​ ​b​u​t​ ​n​o​t​ ​a​ ​g​a​m​e​r​,​ ​f​a​v​o​r​i​t​e​ ​g​a​m​e​ ​g​e​n​r​e​s​ ​a​r​e​ ​R​P​G​,​ ​O​p​e​n​ ​W​o​r​l​d​,​ ​a​n​d​ ​F​P​S​ ​e​s​p​e​c​i​a​l​l​y​ ​t​h​o​s​e​ ​w​i​t​h​ ​c​o​m​p​l​e​x​ ​s​t​o​r​i​e​s​ ​o​r​ ​m​u​l​t​i​p​l​e​ ​e​n​d​i​n​g​s​.​ ​A​l​s​o​ ​l​i​k​e​ ​t​o​ ​w​a​t​c​h​ ​m​o​v​i​e​s​,​ ​f​a​v​o​r​i​t​e​ ​m​o​v​i​e​ ​g​e​n​r​e​s​ ​o​r​ ​s​t​o​r​i​e​s​ ​a​r​e​ ​ ​H​o​r​r​o​r​,​ ​S​c​i​-​F​i​,​ ​M​y​s​t​e​r​y​,​ ​a​n​d​ ​P​s​y​c​h​o​l​o​g​i​c​a​l​.​ ​e​s​p​e​c​i​a​l​l​y​ ​t​h​o​s​e​ ​w​i​t​h​ ​p​o​s​t​ ​a​p​o​c​a​l​y​p​t​i​c​ ​t​h​e​m​e​s​.​<​/​p​>​
​ ​ ​<​p​>​I​ ​e​n​j​o​y​ ​c​o​f​f​e​e​ ​a​l​m​o​s​t​ ​e​v​e​r​y​ ​d​a​y​,​ ​b​u​t​ ​I​'​m​ ​n​o​t​ ​a​ ​c​o​f​f​e​e​ ​j​u​n​k​i​e​.​ ​A​l​s​o​ ​l​i​k​e​ ​s​p​i​c​y​ ​f​o​o​d​ ​e​v​e​n​ ​t​h​o​u​g​h​ ​i​t​ ​o​f​t​e​n​ ​m​a​k​e​s​ ​m​y​ ​s​t​o​m​a​c​h​ ​h​u​r​t​.​<​/​p​>​
​ ​ ​<​p​>​M​y​ ​f​a​v​o​r​i​t​e​ ​V​t​u​b​e​r​ ​i​s​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​c​l​a​s​s​=​"​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​y​o​u​t​u​b​e​.​c​o​m​/​c​h​a​n​n​e​l​/​U​C​M​w​G​H​R​0​B​T​Z​u​L​s​m​j​Y​_​N​T​5​P​w​g​"​>​N​i​n​o​m​a​e​ ​I​n​a​&​a​p​o​s​;​n​i​s​<​/​a​>​,​ ​c​a​u​s​e​ ​s​h​e​ ​i​s​ ​t​a​l​e​n​t​e​d​,​ ​c​h​e​a​r​f​u​l​,​ ​a​n​d​ ​w​h​o​l​e​s​o​m​e​.​ ​A​l​s​o​ ​e​l​d​r​i​t​c​h​/​c​o​s​m​i​c​ ​h​o​r​r​o​r​ ​c​o​n​c​e​p​t​ ​i​s​ ​s​o​o​o​o​ ​c​o​o​l​.​<​/​p​>​
​ ​ ​<​p​>​I​'​m​ ​s​i​n​g​l​e​ ​f​o​r​ ​a​ ​f​a​c​t​,​ ​b​u​t​ ​I​'​m​ ​n​o​t​ ​a​n​ ​i​n​c​e​l​,​ ​b​e​c​a​u​s​e​ ​m​y​ ​t​y​p​e​ ​i​s​ ​a​ ​b​i​t​ ​c​o​m​p​l​e​x​.​ ​B​u​t​ ​i​f​ ​I​ ​c​a​n​ ​c​l​o​n​e​ ​m​y​s​e​l​f​,​ ​m​a​y​b​e​ ​I​ ​w​o​u​l​d​ ​m​a​r​r​y​ ​m​y​s​e​l​f​ ​\​j​k​.​<​/​p​>​
​ ​ ​<​p​>​I​ ​w​a​n​t​ ​t​o​ ​b​e​ ​a​b​l​e​ ​t​o​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​t​h​e​ ​L​i​n​u​x​ ​k​e​r​n​e​l​ ​o​r​ ​o​t​h​e​r​ ​O​p​e​n​ ​S​o​u​r​c​e​ ​s​o​f​t​w​a​r​e​ ​o​n​e​ ​d​a​y​.​ ​O​n​g​o​i​n​g​ ​e​f​f​o​r​t​s​ ​a​r​e​ ​l​e​a​r​n​i​n​g​ ​l​o​w​ ​l​e​v​e​l​ ​p​r​o​g​r​a​m​m​i​n​g​ ​l​a​n​g​u​a​g​e​ ​(​R​u​s​t​)​ ​a​n​d​ ​l​e​a​r​n​i​n​g​ ​t​o​ ​c​o​m​m​u​n​i​c​a​t​e​ ​b​e​t​t​e​r​.​<​/​p​>​
​ ​ ​<​p​>​A​l​s​o​ ​l​i​k​e​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​e​n​.​w​i​k​i​p​e​d​i​a​.​o​r​g​/​w​i​k​i​/​A​l​t​e​r​n​a​t​e​_​r​e​a​l​i​t​y​_​g​a​m​e​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​c​l​a​s​s​=​"​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​>​A​R​G​<​/​a​>​,​ ​s​o​ ​l​e​t​s​ ​m​i​m​i​c​ ​o​n​e​.​ ​L​i​m​i​n​a​l​ ​S​p​a​c​e​,​ ​W​e​i​r​d​ ​C​o​r​e​,​ ​b​r​r​r​r​.​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​x​s​"​>​
​ ​ ​L​a​s​t​l​y​,​ ​t​h​e​r​e​ ​a​r​e​ ​s​o​m​e​ ​e​a​s​t​e​r​ ​e​g​g​s​ ​o​n​ ​t​h​i​s​ ​w​e​b​s​i​t​e​,​ ​m​a​y​b​e​ ​y​o​u​ ​c​a​n​ ​l​o​o​k​ ​f​o​r​ ​t​h​e​m​ ​i​f​ ​y​o​u​ ​h​a​v​e​ ​t​o​o​ ​m​u​c​h​ ​f​r​e​e​ ​t​i​m​e​.​
​ ​ ​<​a​ ​c​l​a​s​s​=​"​t​e​x​t​-​m​a​i​n​-​6​0​0​ ​d​e​c​o​r​a​t​i​o​n​-​w​h​i​t​e​ ​s​e​l​e​c​t​i​o​n​:​t​e​x​t​-​w​h​i​t​e​ ​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​/​n​o​t​e​"​>​s​e​p​e​r​t​i​ ​i​n​i​<​/​a​>​.​ ​B​u​t​ ​d​o​n​'​t​ ​g​o​ ​t​o​o​ ​d​e​e​p​ ​:​D​<​/​s​p​a​n​>​<​/​p​>
	 */
	MorePersonalMotto: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	Contacts: string
}

export type TranslationFunctions = {
	/**
	 * Walking inside the deep abyss of the emptiness in search of the meaning of life.
	 */
	Quote: () => LocalizedString
	/**
	 * Home
	 */
	TitleHome: () => LocalizedString
	/**
	 * Blog
	 */
	TitleBlog: () => LocalizedString
	/**
	 * Gallery
	 */
	TitleGallery: () => LocalizedString
	/**
	 * Projects
	 */
	TitleProjects: () => LocalizedString
	/**
	 * Notes
	 */
	TitleNotes: () => LocalizedString
	/**
	 * Labs
	 */
	TitleLab: () => LocalizedString
	/**
	 * Me
	 */
	TitleAbout: () => LocalizedString
	/**
	 * About Me
	 */
	AboutMe: () => LocalizedString
	/**
	 * Professional
	 */
	Professional: () => LocalizedString
	/**
	 * <p>Hello, my name is Yuanda I'm a web developer with two years of experience who is passionate about minimalist and absurd design. I have experience in creating websites and web applications using modern technology ecosystems such as React, NextJS, and TailwindCSS.</p>
  <p>Currently working as a <b>Part Time Web Developer</b> at <a target="_blank" rel="noopener noreferrer" class="hover:underline" href="https://informatics.uii.ac.id/student-staff/">Student Staff Universitas Islam Indonesia</a> and sometimes doing <b>freelance</b>.</p>
  <p>Have a high learning spirit, especially about technology and new things. Easily adapt and collaborate with new environments. And love to share about the things I love.</p>
  <p>My current goal is to continue expanding my knowledge and skills to one day contribute to the advancement of humanity.</>
	 */
	ProfessionalMotto: () => LocalizedString
	/**
	 * <p>Hello and welcome to my world, my name is Yuanda {redacted}, an optimistic nihilist who loves and relies too much on the internet. Loves philosophy and technology especially the internet as one of the best achievements of humanity.</p>
  <p>Taking value from <i>existential void and emptiness</i>, seeking different perspectives to approach and perceive life.</p>
  <p>I see nihilism not as a hopeless doctrine, but as a catalyst for questioning traditional norms and assumptions.</p>
  <p>However, I understand the importance of collaboration. Trying to understand each other and maintain human relationships is very important. </p>
  <p>Has an interest in technology, philosophy, and psychology. Loves minimalist, absurd, and anti-mainstream design concepts. Also loves to explore and try new things.</p>
  <p>My hobbies are surfing the internet, listening to others, writing, and plunging into the abyss of the void in search of the meaning and significance of life <span class="text-xs">(whatever that means)</span>.</p>
	 */
	PersonalMotto: (arg: { redacted: ReactNode }) => LocalizedString
	/**
	 * Show more
	 */
	ProfileMore: () => LocalizedString
	/**
	 * <p>Sometimes I like to play CTF or do algorithm problems on Hackerrank.</p>
  <p>Like to play games, but not a gamer, favorite game genres are RPG, Open World, and FPS especially those with complex stories or multiple endings. Also like to watch movies, favorite movie genres or stories are  Horror, Sci-Fi, Mystery, and Psychological. especially those with post apocalyptic themes.</p>
  <p>I enjoy coffee almost every day, but I'm not a coffee junkie. Also like spicy food even though it often makes my stomach hurt.</p>
  <p>My favorite Vtuber is <a target="_blank" rel="noopener noreferrer" class="hover:underline" href="https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg">Ninomae Ina&apos;nis</a>, cause she is talented, chearful, and wholesome. Also eldritch/cosmic horror concept is soooo cool.</p>
  <p>I'm single for a fact, but I'm not an incel, because my type is a bit complex. But if I can clone myself, maybe I would marry myself \jk.</p>
  <p>I want to be able to contribute to the Linux kernel or other Open Source software one day. Ongoing efforts are learning low level programming language (Rust) and learning to communicate better.</p>
  <p>Also like <a href="https://en.wikipedia.org/wiki/Alternate_reality_game" target="_blank" rel="noopener noreferrer" class="hover:underline">ARG</a>, so lets mimic one. Liminal Space, Weird Core, brrrr. <span class="text-xs">
  Lastly, there are some easter eggs on this website, maybe you can look for them if you have too much free time.
  <a class="text-main-600 decoration-white selection:text-white hover:underline" href="/note">seperti ini</a>. But don't go too deep :D</span></p>
	 */
	MorePersonalMotto: () => LocalizedString
	/**
	 * Contacts
	 */
	Contacts: () => LocalizedString
}

export type Formatters = {}
