// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { ReactNode } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​a​l​k​i​n​g​ ​i​n​s​i​d​e​ ​t​h​e​ ​d​e​e​p​ ​a​b​y​s​s​ ​o​f​ ​t​h​e​ ​e​m​p​t​i​n​e​s​s​ ​i​n​ ​s​e​a​r​c​h​ ​o​f​ ​t​h​e​ ​m​e​a​n​i​n​g​ ​o​f​ ​l​i​f​e​.
	 */
	Quote: string
	/**
	 * A​b​o​u​t​ ​M​e
	 */
	AboutMe: string
	/**
	 * P​r​o​f​e​s​s​i​o​n​a​l
	 */
	Professional: string
	/**
	 * <​p​>​H​e​l​l​o​,​ ​m​y​ ​n​a​m​e​ ​i​s​ ​Y​u​a​n​d​a​ ​I​'​m​ ​a​ ​w​e​b​ ​d​e​v​e​l​o​p​e​r​ ​w​i​t​h​ ​t​w​o​ ​y​e​a​r​s​ ​o​f​ ​e​x​p​e​r​i​e​n​c​e​ ​w​h​o​ ​i​s​ ​p​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​m​i​n​i​m​a​l​i​s​t​ ​a​n​d​ ​a​b​s​u​r​d​ ​d​e​s​i​g​n​.​ ​I​ ​h​a​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​c​r​e​a​t​i​n​g​ ​w​e​b​s​i​t​e​s​ ​a​n​d​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​u​s​i​n​g​ ​m​o​d​e​r​n​ ​t​e​c​h​n​o​l​o​g​y​ ​e​c​o​s​y​s​t​e​m​s​ ​s​u​c​h​ ​a​s​ ​R​e​a​c​t​,​ ​N​e​x​t​J​S​,​ ​a​n​d​ ​T​a​i​l​w​i​n​d​C​S​S​.​<​/​p​>​
​ ​ ​<​p​>​C​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​a​ ​<​b​>​P​a​r​t​ ​T​i​m​e​ ​W​e​b​ ​D​e​v​e​l​o​p​e​r​<​/​b​>​ ​a​t​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​c​l​a​s​s​=​"​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​i​n​f​o​r​m​a​t​i​c​s​.​u​i​i​.​a​c​.​i​d​/​s​t​u​d​e​n​t​-​s​t​a​f​f​/​"​>​S​t​u​d​e​n​t​ ​S​t​a​f​f​ ​U​n​i​v​e​r​s​i​t​a​s​ ​I​s​l​a​m​ ​I​n​d​o​n​e​s​i​a​<​/​a​>​ ​a​n​d​ ​s​o​m​e​t​i​m​e​s​ ​d​o​i​n​g​ ​<​b​>​f​r​e​e​l​a​n​c​e​<​/​b​>​.​<​/​p​>​
​ ​ ​<​p​>​H​a​v​e​ ​a​ ​h​i​g​h​ ​l​e​a​r​n​i​n​g​ ​s​p​i​r​i​t​,​ ​e​s​p​e​c​i​a​l​l​y​ ​a​b​o​u​t​ ​t​e​c​h​n​o​l​o​g​y​ ​a​n​d​ ​n​e​w​ ​t​h​i​n​g​s​.​ ​E​a​s​i​l​y​ ​a​d​a​p​t​ ​a​n​d​ ​c​o​l​l​a​b​o​r​a​t​e​ ​w​i​t​h​ ​n​e​w​ ​e​n​v​i​r​o​n​m​e​n​t​s​.​ ​A​n​d​ ​l​o​v​e​ ​t​o​ ​s​h​a​r​e​ ​a​b​o​u​t​ ​t​h​e​ ​t​h​i​n​g​s​ ​I​ ​l​o​v​e​.​<​/​p​>​
​ ​ ​<​p​>​M​y​ ​c​u​r​r​e​n​t​ ​g​o​a​l​ ​i​s​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​e​x​p​a​n​d​i​n​g​ ​m​y​ ​k​n​o​w​l​e​d​g​e​ ​a​n​d​ ​s​k​i​l​l​s​ ​t​o​ ​o​n​e​ ​d​a​y​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​t​h​e​ ​a​d​v​a​n​c​e​m​e​n​t​ ​o​f​ ​h​u​m​a​n​i​t​y​.​<​/​>
	 */
	ProfessionalMotto: string
	/**
	 * <​p​>​H​e​l​l​o​ ​a​n​d​ ​w​e​l​c​o​m​e​ ​t​o​ ​m​y​ ​w​o​r​l​d​,​ ​m​y​ ​n​a​m​e​ ​i​s​ ​Y​u​a​n​d​a​ ​{​r​e​d​a​c​t​e​d​}​,​ ​a​n​ ​o​p​t​i​m​i​s​t​i​c​ ​n​i​h​i​l​i​s​t​ ​w​h​o​ ​l​o​v​e​s​ ​a​n​d​ ​r​e​l​i​e​s​ ​t​o​o​ ​m​u​c​h​ ​o​n​ ​t​h​e​ ​i​n​t​e​r​n​e​t​.​ ​L​o​v​e​s​ ​p​h​i​l​o​s​o​p​h​y​ ​a​n​d​ ​t​e​c​h​n​o​l​o​g​y​ ​e​s​p​e​c​i​a​l​l​y​ ​t​h​e​ ​i​n​t​e​r​n​e​t​ ​a​s​ ​o​n​e​ ​o​f​ ​t​h​e​ ​b​e​s​t​ ​a​c​h​i​e​v​e​m​e​n​t​s​ ​o​f​ ​h​u​m​a​n​i​t​y​.​<​/​p​>​
​ ​ ​<​p​>​T​a​k​i​n​g​ ​v​a​l​u​e​ ​f​r​o​m​ ​<​i​>​e​x​i​s​t​e​n​t​i​a​l​ ​v​o​i​d​ ​a​n​d​ ​e​m​p​t​i​n​e​s​s​<​/​i​>​,​ ​s​e​e​k​i​n​g​ ​d​i​f​f​e​r​e​n​t​ ​p​e​r​s​p​e​c​t​i​v​e​s​ ​t​o​ ​a​p​p​r​o​a​c​h​ ​a​n​d​ ​p​e​r​c​e​i​v​e​ ​l​i​f​e​.​<​/​p​>​
​ ​ ​<​p​>​I​ ​s​e​e​ ​n​i​h​i​l​i​s​m​ ​n​o​t​ ​a​s​ ​a​ ​h​o​p​e​l​e​s​s​ ​d​o​c​t​r​i​n​e​,​ ​b​u​t​ ​a​s​ ​a​ ​c​a​t​a​l​y​s​t​ ​f​o​r​ ​q​u​e​s​t​i​o​n​i​n​g​ ​t​r​a​d​i​t​i​o​n​a​l​ ​n​o​r​m​s​ ​a​n​d​ ​a​s​s​u​m​p​t​i​o​n​s​.​<​/​p​>​
​ ​ ​<​p​>​H​o​w​e​v​e​r​,​ ​I​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​i​m​p​o​r​t​a​n​c​e​ ​o​f​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​.​ ​T​r​y​i​n​g​ ​t​o​ ​u​n​d​e​r​s​t​a​n​d​ ​e​a​c​h​ ​o​t​h​e​r​ ​a​n​d​ ​m​a​i​n​t​a​i​n​ ​h​u​m​a​n​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​ ​i​s​ ​v​e​r​y​ ​i​m​p​o​r​t​a​n​t​.​ ​<​/​p​>​
​ ​ ​<​p​>​H​a​s​ ​a​n​ ​i​n​t​e​r​e​s​t​ ​i​n​ ​t​e​c​h​n​o​l​o​g​y​,​ ​p​h​i​l​o​s​o​p​h​y​,​ ​a​n​d​ ​p​s​y​c​h​o​l​o​g​y​.​ ​L​o​v​e​s​ ​m​i​n​i​m​a​l​i​s​t​,​ ​a​b​s​u​r​d​,​ ​a​n​d​ ​a​n​t​i​-​m​a​i​n​s​t​r​e​a​m​ ​d​e​s​i​g​n​ ​c​o​n​c​e​p​t​s​.​ ​A​l​s​o​ ​l​o​v​e​s​ ​t​o​ ​e​x​p​l​o​r​e​ ​a​n​d​ ​t​r​y​ ​n​e​w​ ​t​h​i​n​g​s​.​<​/​p​>​
​ ​ ​<​p​>​M​y​ ​h​o​b​b​i​e​s​ ​a​r​e​ ​s​u​r​f​i​n​g​ ​t​h​e​ ​i​n​t​e​r​n​e​t​,​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​o​t​h​e​r​s​,​ ​w​r​i​t​i​n​g​,​ ​a​n​d​ ​p​l​u​n​g​i​n​g​ ​i​n​t​o​ ​t​h​e​ ​a​b​y​s​s​ ​o​f​ ​t​h​e​ ​v​o​i​d​ ​i​n​ ​s​e​a​r​c​h​ ​o​f​ ​t​h​e​ ​m​e​a​n​i​n​g​ ​a​n​d​ ​s​i​g​n​i​f​i​c​a​n​c​e​ ​o​f​ ​l​i​f​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​x​s​"​>​(​w​h​a​t​e​v​e​r​ ​t​h​a​t​ ​m​e​a​n​s​)​<​/​s​p​a​n​>​.​<​/​p​>
	 * @param {ReactNode} redacted
	 */
	PersonalMotto: RequiredParams<'redacted'>
}

export type TranslationFunctions = {
	/**
	 * Walking inside the deep abyss of the emptiness in search of the meaning of life.
	 */
	Quote: () => LocalizedString
	/**
	 * About Me
	 */
	AboutMe: () => LocalizedString
	/**
	 * Professional
	 */
	Professional: () => LocalizedString
	/**
	 * <p>Hello, my name is Yuanda I'm a web developer with two years of experience who is passionate about minimalist and absurd design. I have experience in creating websites and web applications using modern technology ecosystems such as React, NextJS, and TailwindCSS.</p>
  <p>Currently working as a <b>Part Time Web Developer</b> at <a target="_blank" rel="noopener noreferrer" class="hover:underline" href="https://informatics.uii.ac.id/student-staff/">Student Staff Universitas Islam Indonesia</a> and sometimes doing <b>freelance</b>.</p>
  <p>Have a high learning spirit, especially about technology and new things. Easily adapt and collaborate with new environments. And love to share about the things I love.</p>
  <p>My current goal is to continue expanding my knowledge and skills to one day contribute to the advancement of humanity.</>
	 */
	ProfessionalMotto: () => LocalizedString
	/**
	 * <p>Hello and welcome to my world, my name is Yuanda {redacted}, an optimistic nihilist who loves and relies too much on the internet. Loves philosophy and technology especially the internet as one of the best achievements of humanity.</p>
  <p>Taking value from <i>existential void and emptiness</i>, seeking different perspectives to approach and perceive life.</p>
  <p>I see nihilism not as a hopeless doctrine, but as a catalyst for questioning traditional norms and assumptions.</p>
  <p>However, I understand the importance of collaboration. Trying to understand each other and maintain human relationships is very important. </p>
  <p>Has an interest in technology, philosophy, and psychology. Loves minimalist, absurd, and anti-mainstream design concepts. Also loves to explore and try new things.</p>
  <p>My hobbies are surfing the internet, listening to others, writing, and plunging into the abyss of the void in search of the meaning and significance of life <span class="text-xs">(whatever that means)</span>.</p>
	 */
	PersonalMotto: (arg: { redacted: ReactNode }) => LocalizedString
}

export type Formatters = {}
