// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​a​l​k​i​n​g​ ​i​n​s​i​d​e​ ​t​h​e​ ​d​e​e​p​ ​a​b​y​s​s​ ​o​f​ ​t​h​e​ ​e​m​p​t​i​n​e​s​s​ ​i​n​ ​s​e​a​r​c​h​ ​o​f​ ​t​h​e​ ​m​e​a​n​i​n​g​ ​o​f​ ​l​i​f​e​.
	 */
	Quote: string
}

export type TranslationFunctions = {
	/**
	 * Walking inside the deep abyss of the emptiness in search of the meaning of life.
	 */
	Quote: () => LocalizedString
}

export type Formatters = {}
