name: neroi-me-mono

services:
  neroi-db:
    image: mysql:9.0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ../.env
    # volumes:
    #   - ./dump-neroi-me-202403111229.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: "network-neroi-me"