services:
  neroi-db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - ../.env
    shm_size: 256mb
    # volumes:
    #   - ./dump-neroi-me-202403111229.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: "network-neroi-me"